version: "3.9"
services:
  db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    #volumes:
    #- /opt/mysql_data:/var/lib/mysql
    ports:
    - 3306:3306
    - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: dbrootpass
  www:
    depends_on:
    - db
    image: php:8.1.2-apache
    #volumes:
    #- "Path/to/your/PHP/.:/var/www/html"
    ports:
    - 80:80
    - 443:443
  phpmyadmin:
    depends_on:
    - db
    image: phpmyadmin:5.1.1
    restart: always
    ports:
    - 8080:80
    environment:
    - PMA_ARBITRARY=1
